---
version: "3.2"

services:
  prometheus:
    build:
      context: .
      dockerfile: prometheus/Dockerfile
    hostname: "$PROMETHEUS_HOST"
    ports:
      - "$PROMETHEUS_SERIVCE_PORT:9090"

  grafana:
    build:
      context: .
      dockerfile: grafana/Dockerfile
      args:
        GRAFANA_ADMIN_USERNAME: "$GRAFANA_ADMIN_USERNAME"
        GRAFANA_ADMIN_PASSWORD: "$GRAFANA_ADMIN_PASSWORD"
        GRAFANA_SERVICE_PORT: "$GRAFANA_SERVICE_PORT"
        PROMETHEUS_HOST: "$PROMETHEUS_HOST"
        PROMETHEUS_SERIVCE_PORT: "$PROMETHEUS_SERIVCE_PORT"
    hostname: "$GRAFANA_HOST"
    ports:
      - "$GRAFANA_SERVICE_PORT:$GRAFANA_SERVICE_PORT"
    depends_on:
      - prometheus