{
 "title": "iRODS CSI Driver Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "# of iRODS FUSE Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(irodsfs_pool_grpc_clients)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# of Active iRODS Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(irodsfs_pool_occupied_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of iRODS Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irodsfs_pool_open_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of iRODS File Handles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(irodsfs_pool_open_file_handles)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iRODS Bytes Sent (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(delta(irodsfs_pool_bytes_sent_total[5m])) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iRODS Bytes Received (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(delta(irodsfs_pool_bytes_received_total[5m])) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iRODS Pool Content Cache Hit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(delta(irodsfs_pool_cache_hit_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iRODS RPC Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(irodsfs_pool_request_response_failures_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iRODS Connection Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(irodsfs_pool_connection_failures_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iRODS CSI Driver Volume Mount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(irods_csi_driver_volume_mount)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}